### ISSUE TITLE
No candidate list dialog in debian 12

### ISSUE THREAD

**Issue by reply2future** [Cangjians/ibus-cangjie#102]
## Information

System: debian 12
Package: ibus-cangjie
Version: 2.4-7
Priority: optional
Section: utils
Maintainer: Debian Input Method Team <debian-input-method@lists.debian.org>
Installed-Size: 122 kB
Depends: gir1.2-ibus-1.0, ibus (>= 1.4.1), python3-gi, python3-pycangjie (>= 1.0), dconf-gsettings-backend | gsettings-backend, python3:any
Homepage: https://cangjians.github.io/projects/ibus-cangjie/
Download-Size: 19.7 kB
APT-Manual-Installed: yes 

## Reproduct
[Screencast from 2023-11-14 14-40-19.webm](https://github.com/Cangjians/ibus-cangjie/assets/6359152/1cd71137-9fb3-45e2-9c1d-611218a21805)

**Comment by mbridon** [comment]
Hi @reply2future and thank you for the bug report.

I'll investigate what's going on, but in the meantime, we moved away from github for all the *cangjie stack to gitlab.freedesktop.org, do you think you can move this bug report there? 😕

**Comment by mc776** [comment]
Is this the URL? https://gitlab.freedesktop.org/cangjie/libcangjie

**Comment by mbridon** [comment]
No, this is the new URL for libcangjie. 😉 

The new URL for pycangjie is https://gitlab.freedesktop.org/cangjie/pycangjie and ibus-cangjie is https://gitlab.freedesktop.org/cangjie/ibus-cangjie 😄 

Sorry for the way we handled the move, not mentioning it well, it's kind of still in progress 😕

**Comment by reply2future** [comment]
move to there https://gitlab.freedesktop.org/cangjie/ibus-cangjie/-/issues/104
