### ISSUE TITLE
py-compile script uses "import imp", which is removed in Python 3.12, causes build failure

### ISSUE THREAD

**Issue by hosiet** [Cangjians/ibus-cangjie#103]
The current embedded `py-compile` script was from more than 10 years ago, and its execution during package building will fail with Python 3.12 due to the removal of `imp` module by Python. Please refresh the configure scripts to avoid this issue. Thanks!

**Comment by hosiet** [comment]
I should have mentioned that this applies to the released tarball, `ibus-cangjie-2.4.tar.xz`, not the files managed by Git.

**Comment by yookoala** [comment]
@hosiet Thanks for the attention to our project.

Please note that we have moved to freedesktop.org's GitLab for our development. Please find the latest source code here:
https://gitlab.freedesktop.org/cangjie/ibus-cangjie/

May I ask where the py-compile is embeded?

**Comment by hosiet** [comment]
@yookoala thanks for that info. Can you update the GitHub README to highlight the change of development location? That would be very important to avoid further issues being submitted on GitHub, unaware of location change. Archiving the GitHub project after the README update is even better.

The py-compile script is embedded in https://github.com/Cangjians/ibus-cangjie/releases/download/v2.4/ibus-cangjie-2.4.tar.xz .

**Comment by yookoala** [comment]
@hosiet Will certainly update the README here.

And thanks for the information.

**Comment by mbridon** [comment]
We fixed this a while ago, over at gitlab.freedesktop.org. Please report it there if you find other issues.
