### ISSUE TITLE
Use GtkHeaderBar for the preferences dialog

### ISSUE THREAD

**Issue by bochecha** [Cangjians/ibus-cangjie#47]
GNOME has published some new HIG for various kinds of dialogs.

In our case, we should follow these ones:
https://wiki.gnome.org/Design/HIG/Dialogs#Presentation_Dialogs

Looking at it quickly, it seems that all we'd need to do is to use a GtkHeaderBar with a "X" (close) button, and that should be it.

However, GtkHeaderBar is only available in Gtk >= 3.10, so we'll need to keep the current code as a fallback somehow, or we'd lose compatibility with older platforms.

**Comment by mbridon** [comment]
This has been done with [the move of the setup dialog to Gtk4](https://gitlab.freedesktop.org/cangjie/ibus-cangjie/-/merge_requests/122)
