### ISSUE TITLE
input method icon is not vertically center at at top bar

### ISSUE THREAD

**Issue by yookoala** [Cangjians/ibus-cangjie#48]
Originally reported by @maxiaojun as [Ubuntu bug #1284159](https://bugs.launchpad.net/ubuntu/+source/indicator-keyboard/+bug/1284159). The original message goes:

> See the attached screenshot, default Unity DE is used.
> 
> Chinese (Cangjie) is being used (need to install "ibus-cangjie" and restart IBus).
> 
> Chinese (Quick), which is also provided by ibus-cangjie, has exactly same issue.
> 
> Screenshot:
> ![screenshot from 2014-02-24 23 02 53](https://f.cloud.github.com/assets/91274/2267739/067adde6-9ebe-11e3-9e93-3eb03df5abb3.png)

**Comment by bochecha** [comment]
Canonical abandoned Unity, so let's close this.

It seems a community has gathered to try and maintain Unity. If you work on Unity and would like to work with us on fixing this, do let us know and we can reopen this issue. :slightly_smiling_face:
