### ISSUE TITLE
Cannot use numpad to select character

### ISSUE THREAD

**Issue by yookoala** [Cangjians/ibus-cangjie#49]
Reported by some user on [Ubuntu HK's Facebook group](https://www.facebook.com/groups/ubuntuhk/permalink/695625130484270/?stream_ref=2). User cannot use the number keys on num pad section to select characters.

Since I have no full-size keyboard at home, I cannot verify the issue. I'll test this once I back to office tomorrow.

**Comment by didrocks** [comment]
I have an up to date ubuntu 18.04 machine and I can't reproduce the issue, tested with @bochecha. Do you mind fiddling a little more details?

**Comment by bochecha** [comment]
@universebreaker Are you sure you didn't just forget to enable the "num lock"? :slightly_smiling_face:

**Comment by universebreaker** [comment]
after testing engine.py...it turns out I installed "quick classic" by mistake (which also append a space strangely if I use [space] to select the frist character...), the "quick" one is fine. sorry for that.

**Comment by bochecha** [comment]
@universebreaker Oh, "quick classic" is completely unrelated to ibus-cangjie then. If I recall correctly that's from ibus-table.

Glad to learn that we fixed that problem for good. :slightly_smiling_face:
