### ISSUE TITLE
ibus-cangjie does not respect --libexecdir

### ISSUE THREAD

**Issue by czchen** [Cangjians/ibus-cangjie#58]
From https://bugs.debian.org/746978

In debian, we want to put `ibus-engine-cangjie` to `/usr/lib/ibus` like other ibus packages. However, ibus-cangjie does not use the value set by `--libexecdir` to determine the path of `ibus-engine-cangjie`, thus we cannot change `ibus-engine-cangjie` easily. Please help to support `--libexecdir`, thanks.

**Comment by changwoo** [comment]
Here is an update: Debian ibus package now uses `/usr/libexec`.

In 2014, the Debian policy used FHS 2.1 which had no `/usr/libexec`.  But the current Debian policy uses FHS 3.0 which explicitly specifies `/usr/libexec` as the path for internal executable files.

See https://bugs.debian.org/955227 for another ibus-cangjie package bug

**Comment by mbridon** [comment]
Pretty sure [we've now fixed that](https://gitlab.freedesktop.org/cangjie/ibus-cangjie/-/merge_requests/126)

If the issue still occurs, please open a new one on gitlab.fdo.org. :wink:
