### ISSUE TITLE
Drop the hardcoded gettext package

### ISSUE THREAD

**Issue by bochecha** [Cangjians/ibus-cangjie#7]
One possibility would be to have the `ibus-engine-cangjie` script get it from the `Makefile.am` and then pass it as a parameter.

Not very nice, but that script is already generated at build-time, so it would be better than making `src/config.py` generated as well. (I used to have it that way, and it was annoying)

Can't think about a better way right now, but any idea is welcome. :)

**Comment by mbridon** [comment]
This is being tracked on Gitlab.fdo
