### ISSUE TITLE
feature request - display candidate whatever it possible be

### ISSUE THREAD

**Issue by iravan** [Cangjians/ibus-cangjie#71]
I found that a pretty good feature on my andriod phone cangjie input method.
My phone is samsung. The cangjie of input method should be made by samsung.

I hope ibus-cangjie can also have that feature -
display every possible candidate when user input every cangjie code.
for instance "我".
竹: 竹我粵犥牻犏
竹手: 牛我犥牻生
竹手戈: 我牻犥犏

and the ordering should be by "frequency"

**Comment by yookoala** [comment]
This is controversial.

We've heard people found this "search as you type" behaviour annoying even before the project started. If we're to implement it, we need to have option to turn it on and off. Also we need to make sure it is not hugely impact on the performance.

Need more discussion here.

**Comment by bochecha** [comment]
Isn't this the exact same as #37 ?

**Comment by iravan** [comment]
@bochecha ah yes!
