### ISSUE TITLE
showing the icon in panel incorrectly

### ISSUE THREAD

**Issue by iravan** [Cangjians/ibus-cangjie#73]
Desktop Environment info page

> Window Manager (xfwm4)
> Handles the placement of windows on the screen.
> 
> Panel (xfce4-panel)
> Program launchers, window buttons, applications menu, workspace switcher and more.
> 
> Desktop Manager (xfdesktop)
> Sets the background color or image with optional application menu or icons for minimized applications or launchers, devices and folders.
> 
> File Manager  (thunar)
> A modern file manager for the Unix/Linux desktop, aiming to be easy-to-use and fast.
> 
> Session Manager (xfce4-session)
> Restores your session on startup and allows you to shutdown the computer from Xfce.
> 
> Setting System (xfce4-settings)
> Configuration system to control various aspects of the desktop like appearance, display, keyboard and mouse settings.
> 
> Application Finder (xfce4-appfinder)
> Shows the applications installed on your system in categories, so you can quickly find and launch them.
> 
> Settings Daemon (xfconf)
> D-Bus-based configuration storage system.

Nomal Case of ibus daemon icon 
![default](https://cloud.githubusercontent.com/assets/4957816/17462810/fcb6527a-5cea-11e6-992c-4f7003389c8b.png)

Abnormal : 
![default](https://cloud.githubusercontent.com/assets/4957816/17462815/175df6fa-5ceb-11e6-8863-aad4590ec18b.png)
![default](https://cloud.githubusercontent.com/assets/4957816/17462816/1987c334-5ceb-11e6-8022-cdc9ae1246ae.png)

**Comment by bochecha** [comment]
Basically, our icon is bad, it's a quick thing we did with @yookoala back in the days.

However, both of us use GNOME, and GNOME doesn't use those icons, so none of us has any incentive to fix this. (plus, none of us knows how to properly draw icons :wink: )

I'd be happy to receive a better icon as a patch, though.

**Comment by mbridon** [comment]
This has been going on for so long... We moved away from github to gitlab.freedesktop.org/cangjie/ibus-cangjie a while ago, so please if you want this to ever be fixed report it there.
