### ISSUE TITLE
some char candidate is not visible when near the bottom of screen

### ISSUE THREAD

**Issue by dictcp** [Cangjians/ibus-cangjie#75]
Summary
When I am typing Chinese in gedit (other any other text editor/textarea), part of the ibus char selection window is not visible when the windows is too long (in term of height).

Package versions:
ubuntu 16.04.1
ibus-cangjie-2.4-1

Steps to reproduce:
1. install ubuntu, ibus-cangjie and gedit
2. enable quick input method
3. move the window to the bottom edge of the screen
4. try typing in the address bar
5. partial of the char selection windows was not in the visable screen

Expected behavior: the entire windows should be visible

Reproducible
Always

![candidate_box](https://cloud.githubusercontent.com/assets/1752436/18353497/bec9ff46-7614-11e6-9cf3-3151a0a3eb40.png)

**Comment by dictcp** [comment]
https://github.com/Cangjians/ibus-cangjie/pull/76 works for me

**Comment by bochecha** [comment]
#76 really was the wrong fix for this.

Can you provide a screenshot of the whole screen, I'm having trouble understanding the full problem.

**Comment by dictcp** [comment]
![candidate_box_screen](https://cloud.githubusercontent.com/assets/1752436/18356274/acb27338-761e-11e6-9f99-27b19dbfb6be.png)

since I am using quick, the item in char selection window should be more than 2.

**Comment by dictcp** [comment]
that nonsense PR should not be accepted for sure :P

and actually I am suspecting it is upstream issue - maybe got fixed and thus ubuntu only issue

(I will use that nonsense PR in my daily life) and I will try to reproduce it in other platform to confirm whether it is a upstream issue.

**Comment by antonyho** [comment]
Can’t reproduce the problem on Manjaro GNOME.

**Comment by bochecha** [comment]
I can reproduce with gedit, placing the window at the bottom of the screen.

![bad](https://cloud.githubusercontent.com/assets/272170/18409284/a8d870a2-7743-11e6-9e3a-23efdb68f325.png)

One thing to note is that ibus-cangjie is not the thing that actually draws the candidate popup on the screen, that's the « ibus panel ».

I'm using GNOME, so for me the « ibus panel » is the GNOME Shell. On other desktops it might be something else.

I don't think there's anything we can do about this on the ibus-cangjie side, though.

Can you open a bug report against GNOME Shell in https://bugzilla.gnome.org?

**Comment by bochecha** [comment]
@dictcp I don't know whether you reported a bug, but I ended up doing it: https://bugzilla.gnome.org/show_bug.cgi?id=771724

I talked about it with some GNOME folks, and one of them will try and fix it.

Closing this now, thanks for the original bug report!
