### ISSUE TITLE
Help the user learn Cangjie - Display the code on wildcard usage

### ISSUE THREAD

**Issue by bochecha** [Cangjians/ibus-cangjie#8]
Cangjie is really tough to learn.

One way to help people learn it is to **display the proper code when they use a wildcard** (`*`).

It could be done different ways, I can think of two:
1. Next to each character in the suggestion popup.
   
   This has the benefit that it's trivial to implement (we already get the real codes from libcangjie2 when we get the possible characters for a code).
   
   However, @yookoala felt that it might be slightly disturbing, as the user would have additional information next to the suggestions, which might make it harder to quickly spot the desired one.
2. In a popup, for a brief instant after committing a character.
   
   This was suggested by @yookoala, and it's apparently what some other OS does.

Number 2 would be a bit tougher to implement, so I'm inclined to start with number 1, and if it turns out too distracting for users, we can improve it by implementing number 2 instead. :)

I feel this would really help users who are not always sure of the proper code for a character: they can already use a wildcard, but this would give them a way to learn the right code for the next time.

This would especially be useful for Quick users who want to start using Cangjie.

**Comment by mbridon** [comment]
This is being tracked on gitlab.fdo now, and is about to finally be released in ibus-cangjie 2.5 :tada:
