### ISSUE TITLE
Move to Gitlab

### ISSUE THREAD

**Issue by bochecha** [Cangjians/ibus-cangjie#80]
*Note: This issue is for libcangjie, pycangjie and ibus-cangjie*

How would you feel about moving the Cangjians repos somewhere to a Gitlab hosting?

The advantages of that I can see:

1.  Gitlab is free software (well, it's open-core), and I'm convinced [we should use free software tools as much as possible when developing our own free software](https://mako.cc/writing/hill-free_tools.html).

    The version at https://gitlab.com includes some proprietary extensions, but there are other hostings which only deploy the free software version, for example https://framagit.org, which is hosted by Framasoft, a French NPO whose goal is to promote free software and [decentralise the Internet](https://degooglisons-internet.org/)

2.  Gitlab CI is much more powerful than Travis.

    For example, it would allow us to pick which Docker image we want to build on without having to make our own `Dockerfile`s.

    We could even configure it to build on multiple OS/architectures at the same time (think big/little endian errors).

    Gitlab CI also isn't limited to running a single job, it can run multiple ones in parallel. For example we could run one job for the unit tests, and one job for some statical analysis (e.g pyflakes for Python, clang for C). Sky is the limit!

3.  Gitlab can import everything from Github: the code, the issues, the pull requests, ... So we wouldn't lose any history if everything goes well with the import.

However we would lose the "network effect" which makes it easier for people to contribute to our repositories as they most likely already have an account on Github, but... I care less and less about that, and in fact I'd rather stop contributing to that network effect on a proprietary platform.

I'm not sure about the website either, Gitlab has a "Pages" system equivalent to the Github one (except it seems to support more things than just Jekyll), but I guess that depends on the hosting, some might not offer the service. But we could keep cangjians.github.io anyway, at least for the time being.

**Comment by yookoala** [comment]
Is it possible if we only rely Gitlab for CI testing, and to source code distributing or version control.

I'd prefer us to stay on Github for development and issue tracking. The community in Github is much more active than in Gitlab. I suggest we can make repositories to test on Gitlab before deciding.

**Comment by yookoala** [comment]
Another alternative is use Drone.io for CI:

* It's core is also [open sourced][drone.io].
* It support [matrix definition], which support multiple docker image builds.
* It support Github.

[drone.io]: https://github.com/drone/drone
[matrix definition]: http://readme.drone.io/usage/matrix-guide/

**Comment by bochecha** [comment]
We have started migrating to https://gitlab.freedesktop.org/cangjie/ !

Let's use this ticket to keep track of what still needs to be done:

*   [x] Migrate build-essential
    *   [x] import the code, issues, merge requests, …
    *   [x] adopt the Freedesktop.org code of conduct
    *   [x] make it build images and push them to the Gitlab registry
*   [x] Migrate libcangjie
    *   [x] import the code, issues, merge requests, …
    *   [x] adopt the Freedesktop.org code of conduct
    *   [x] redo its CI with Gitlab CI
*   [x] Migrate pycangjie
    *   [x] import the code, issues, merge requests, …
    *   [x] adopt the Freedesktop.org code of conduct
    *   [ ] redo its CI with Gitlab CI
*   [x] Migrate ibus-cangjie
    *   [x] import the code, issues, merge requests, …
    *   [x] adopt the Freedesktop.org code of conduct
    *   [x] redo its CI with Gitlab CI
*   [x] Redo the website with Gitlab Pages
    *   [x] keep a redirect from https://cangjians.github.io to the new site
    *   [x] update all references to the website URL in all projects

**Comment by mbridon** [comment]
So, I was wondering whether gitlab.freedesktop.org would accept us, and I don't remember whether I had actually ask them at the time, so I just did it now, we'll see how it goes :shrug:

**Comment by mbridon** [comment]
I've been told by a freedesktop developper the following : 

```
<bochecha> hi everyone, hope you're all good :)
<bochecha> I was wondering about gitlab.freedesktop.org, is it opened for new projects? or just for the offocial xdg things like specs, wayland, etc... ?
<bochecha> (I had started migrating some projects away from github some time ago to gitlab.freedesktop.org as I'm trying to move away from github and my projects (a Linux input method for Chinese) would be a better fit for something like gitlab.freedesktop.org, but that's assuming you would all accept it there, and I don't think I ever asked for permission at the time :-/
<bochecha> and after I started, I got sick and spent 2 years in a hospital for reeducation, and so I could never get back to it... :(
<bochecha> so, here I am, belatedly, adking whether gitlab.freedesktop.org would welcome the *cangjie projects (libcangjie, pycangjie and ibus-cangjie) :)
pkira (~pkira@134.191.197.172) vient de rentrer
<bentiss> bochecha: I'm not in the board but this looks like a compatible with fdo project, so I don't see a reason why refusing it.
<bentiss> bochecha: please open a bug against freedesktop/freedesktop requesting for a new group ("new project" template)
[...]
<bochecha> bentiss, I have a new group already : https://gitlab.freedesktop.org/cangjie/
<bochecha> there are a few projects inside already :)
<bentiss> bochecha: then you are all set :)
<bochecha> ah ok, so I can go ahead and import the other projects ?
<bochecha> it's not a problem I nee
<bentiss> bochecha: yes, you are owner of this group, and we trust you to manage it properly :)
<bochecha> it's not a problem I never ask for permission at the time ?
<bochecha> maybe I did, i just can't remember, because brain issue at the time when I got sick :(
<bentiss> it was probably automatically created when the big migration started
<bentiss> or it was asked
<bentiss> but anyway, the group is there, you are free to use it
<bochecha> ok, thank you :)
```
