### ISSUE TITLE
Arch linux ibus-cangjie package seems to be not working after updating to Python3.6

### ISSUE THREAD

**Issue by pterodragon** [Cangjians/ibus-cangjie#81]
ibus-cangjie still resides in /usr/lib/python3.5/site-packages/ 

I used cangjie for many years and really appreciate you all implement this in ibus after I use linux :)

**Comment by bochecha** [comment]
> Then the package needs to be rebuilt.

Not something we can do here upstream, it's up to the Arch package maintainers.

**Comment by pterodragon** [comment]
Isn't Antony the maintainer of the package there?
BTW, a rebuilt doesn't simply work

**Comment by bochecha** [comment]
You probably need to rebuild pycangjie first, then ibus-cangjie.

@antonyho maintains the AUR packages, which get built on your machine when you install them.

They are not pre-built packages, therefore you need to rebuild them yourself.

**Comment by pterodragon** [comment]
Hey you are right, I forgot to clean and rebuild the dependencies 
Thank you for your help :)

**Comment by bochecha** [comment]
> Thank you for your help :)

No problem. Glad it works for you now! :)

**Comment by antonyho** [comment]
Sorry, I was too late to see this issue.
Yes, simply rebuild from pycangjie and then ibus-cangjie should fix your issue.

**Comment by antonyho** [comment]
Sorry, I was too late to see this issue.
Yes, simply rebuild from pycangjie and then ibus-cangjie should fix your issue.

Antony
