### ISSUE TITLE
Build failed in Manjaro Linux

### ISSUE THREAD

**Issue by iravan** [Cangjians/ibus-cangjie#82]
python version : 3.6

`yaourt ibus-cangjie`

> checking the cangjie Python module... no
> configure: error: Please install the cangjie Python module
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ==> ERROR: Makepkg was unable to build ibus-cangjie.

**Comment by bochecha** [comment]
Yeah, well, you need to install pycangjie as well.

I don't know how it's packaged in Manjaro.

That seems like a packaging bug, pycangjie really should be a dependency of ibus-cangjie.

Can you report it to the Manjaro developers?

**Comment by antonyho** [comment]
Would you check whether Manjaro AUR has pycangjie package or not?

**Comment by antonyho** [comment]
Good to know the problem has been solved. But would you describe the steps to reproduce this problem and the steps to solve it. For those who come into there from search engine use as a reference?
Appreciated!

**Comment by iravan** [comment]
I am trying to reproduce the problem.
I install a Manjaro Linux image in virtualbox and trying to install ibus-cangjie.
But I discover that I failed on the installation of ibus-cangjie.


that's what the installation breaks : 
`==> Continue building python-pycangjie ? [Y/n]
==> ------------------------------------------
==> Y

==> Building and installing package
==> Making package: python-pycangjie 1.2-1 (Tue Jan 31 20:05:28 HKT 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found cangjie-1.2.tar.xz
  -> Found 361bb413203fd43bab624d98edf6f7d20ce6bfd3.patch
==> Validating source files with sha256sums...
    cangjie-1.2.tar.xz ... Passed
    361bb413203fd43bab624d98edf6f7d20ce6bfd3.patch ... Skipped
==> Extracting sources...
  -> Extracting cangjie-1.2.tar.xz with bsdtar
==> Starting prepare()...
patching file Makefile.am
==> Removing existing $pkgdir/ directory...
==> Starting build()...
+ libtoolize --automake --copy
+ aclocal -I m4
+ autoheader
+ automake --add-missing --copy
Makefile.am:18: warning: source file 'src/cangjie/_core.c' is in a subdirectory,
Makefile.am:18: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am:25: warning: source file 'src/cangjie/errors.c' is in a subdirectory,
Makefile.am:25: but option 'subdir-objects' is disabled
Makefile.am:32: warning: source file 'src/cangjie/filters.c' is in a subdirectory,
Makefile.am:32: but option 'subdir-objects' is disabled
Makefile.am:39: warning: source file 'src/cangjie/versions.c' is in a subdirectory,
Makefile.am:39: but option 'subdir-objects' is disabled
+ autoconf
+ ./configure --prefix=/usr
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBCANGJIE... yes
checking for a Python interpreter with version >= 3.2.3... python
checking for python... /usr/bin/python
checking for python version... 3.5
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.5/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.5/site-packages
checking for python3.5-config... /usr/bin/python3.5-config
checking python include flags... -I/usr/include/python3.5m -I/usr/include/python3.5m
checking for cython3... /usr/bin/cython3
checking for cython version... recent
File

module
  File "<string>", line 1
    from distutils.version import StrictVersion as ver; import sys; sys.exit(0 if ver("recent
                                                                                            ^
SyntaxError: EOL while scanning string literal
configure: error: Please use cython >= 0.14
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build python-pycangjie.
==> Restart building python-pycangjie ? [y/N]
==> -----------------------------------------
`

**Comment by iravan** [comment]
I install ibus-cangjie and dependences successfully. It seems just the system package issue. Please just ignore my last comment.

**Comment by yookoala** [comment]
@iravan 

Seems like an issue with the `configure.ac` script.
Please help running this command on your virtualbox system and provide the results:
```
/usr/bin/cython3 --version 2>&1 | cut -d" " -f3
```
