### ISSUE TITLE
cangjie.errors.CangjieDBOpenError: Error opening the database

### ISSUE THREAD

**Issue by wnereiz** [Cangjians/ibus-cangjie#83]
"make check" failed with a bunch of these kind of errors in the log
(And ibus-cangjie not work after build, I'm not sure if that is related)

```
ERROR: test_autoclear_on_error (test_cangjie.CangjieTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/ibus-cangjie-2.4/tests/test_cangjie.py", line 32, in setUp
    self.engine = EngineCangjie()
  File "./src/engine.py", line 67, in __init__
    self.init_cangjie()
  File "./src/engine.py", line 125, in init_cangjie
    self.cangjie = cangjie.Cangjie(version, filters)
  File "src/cangjie/_core.pyx", line 109, in cangjie._core.Cangjie.__cinit__ (src/cangjie/_core.c:2332)
  File "src/cangjie/errors.pyx", line 56, in cangjie.errors.handle_error_code (src/cangjie/errors.c:1376)
cangjie.errors.CangjieDBOpenError: Error opening the database
```

python 3.6.0

**Comment by bochecha** [comment]
Hi there, thanks for the bug report. :)

These error messages mean that the tests couldn't find the libcangjie database.

Which version of ibus-cangjie are you building? Is it Git master or a release tarball?

**Comment by wnereiz** [comment]
> Which version of ibus-cangjie are you building? Is it Git master or a release tarball?

Release version 2.4

I'm not sure if it is because OBS handling libcangjie as dependency incorrectly before building ibus-cangjie. I will do some research on it.

**Comment by bochecha** [comment]
> Release version 2.4

Ok, so did you take [the release tarball](https://github.com/Cangjians/ibus-cangjie/releases/download/v2.4/ibus-cangjie-2.4.tar.xz) or the Github auto-generated zip/tarball?

The latter two are known not to work, and we don't support them. Unfortunately I couldn't find a way to tell Github not to make them. 😞 

Make sure you only use [the release tarball](https://github.com/Cangjians/ibus-cangjie/releases/download/v2.4/ibus-cangjie-2.4.tar.xz).

> I'm not sure if it is because OBS

Are you building ibus-cangjie for Opensuse? (that would be great)

**Comment by wnereiz** [comment]
Yes, I confirm it is the release tarball.  And yes I'm building for openSUSE.

Looks like there's problem on the build dependency of my spec file, I'm going to research.

**Comment by bochecha** [comment]
Awesome! Thanks for making openSUSE packages! 👍 

As for the spec files, feel free to take much inspiration from my Fedora packages:

* http://pkgs.fedoraproject.org/cgit/rpms/libcangjie.git/tree/libcangjie.spec
* http://pkgs.fedoraproject.org/cgit/rpms/python3-cangjie.git/tree/python3-cangjie.spec
* http://pkgs.fedoraproject.org/cgit/rpms/ibus-cangjie.git/tree/ibus-cangjie.spec

Not sure they can be taken directly or if adaptations would be needed to account for differences between Fedora and openSUSE, though.

**Comment by wnereiz** [comment]
Yes, I have checked these Fedora specs. There are some differences between Fedora and openSUSE spec macros. And I need to consider packaging policy for OBS.

I think I found the reason for this issue, there is a wrong "Requires" dependency, after I changed it, make check still failed with other errors. But any way this problem solved.
Thank you for the help.

**Comment by bochecha** [comment]
No problem!

Feel free to come and hang in #linux-hk on Freenode, if you need some more real-time help with the packaging.

And once ibus-cangjie is in openSUSE, do send a pull request to add install instructions to the website: https://github.com/Cangjians/cangjians.github.io/blob/master/projects/ibus-cangjie/install.md

😃
