### ISSUE TITLE
PyGIWarning: Gtk was imported without specifying a version first

### ISSUE THREAD

**Issue by wnereiz** [Cangjians/ibus-cangjie#86]
```
$ ibus-setup-cangjie cangjie
/usr/bin/ibus-setup-cangjie:35: PyGIWarning: Gtk was imported without specifying
a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that
the right version gets loaded. 
 from gi.repository import Gtk
/usr/bin/ibus-setup-cangjie:36: PyGIWarning: IBus was imported without specifying
a version first. Use gi.require_version('IBus', '1.0') before import to ensure that
the right version gets loaded.
  from gi.repository import IBus
```
It will not be revealed in "make check", only come out when it is running after installation, and it **does not prevent the program running and the program function**.

This issue is because of a new method to import these gi modules, I have created a patch **[here](https://build.opensuse.org/package/view_file/M17N/ibus-cangjie/fix_import_version.patch?expand=1)**

If you think it is okay, I can help to submit a pull request.

**Comment by bochecha** [comment]
Oh wow, did we never reply to your issue?

I apologize, we should never let issues without response like this for so long. :disappointed: 

A pull request would very much be accepted to fix this.

Your patch looks alright at a quick glance, will review in more details the pull request.

Again, I'm sorry we never replied.
