### ISSUE TITLE
Candidate list unreadable while in dark theme

### ISSUE THREAD

**Issue by wyuenchy** [Cangjians/ibus-cangjie#98]
While using dark theme on kde, the candidate list's font and background are both black which makes the table unreadable, is there any way to solve this?
![image](https://user-images.githubusercontent.com/25601830/82341971-aa4e1c00-9a23-11ea-8b9e-c1fe70a05780.png)

**Comment by yookoala** [comment]
Do you have other ibus input method in your system? Do they share the same issue?

**Comment by wyuenchy** [comment]
i have RIME as well but it does not have the problem

**Comment by yookoala** [comment]
Can you cap a screenshot for the ibus-rime character selection dialog in your environment and post here? They might be doing things differently and we need to know about it.

**Comment by wyuenchy** [comment]
![Screenshot_20200520_222525](https://user-images.githubusercontent.com/25601830/82458056-ce276580-9ae8-11ea-9425-8c2dc03e82c5.png)
this is how it looks in rime

**Comment by yookoala** [comment]
Thanks.

**Comment by wyuenchy** [comment]
after some digging i think its a gtk themeing thing, do you know what attribute in the gtk css i should modify to change the font color?

**Comment by mbridon** [comment]
Hi @wyuenchy, sorry for not answering at all... :disappointed: 

I have no idea how to modify a Gtk CSS, or even how that interacts with KDE theming :shrug: 

Did you eventually figure this out ? If so we can close the issue I guess. If not, we can try asking some KDE folks who might know how this could be fixed ?

In any case, thank you for reaching out about this unfortunate issue, and thank you for the patience all these years. :pray:

**Comment by mbridon** [comment]
So, we moved away from github over to gitlab.freedesktop.org. Please report any bug there.
