### ISSUE TITLE
Cannot open cangjie preference in GNOME 40

### ISSUE THREAD

**Issue by scjlee** [Cangjians/ibus-cangjie#99]
Recently installed Solus GNOME 4.3 which ship with GNOME 40.3. I was trying to change cangjie version via GNOME setting, but the window just refuse to show up. While using ibus-setup command, I got following message after clicking preference under input method tab:

```
/usr/bin/ibus-setup-cangjie:35: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/bin/ibus-setup-cangjie:36: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import IBus
Traceback (most recent call last):
  File "/usr/bin/ibus-setup-cangjie", line 62, in <module>
    Setup(args.engine, datadir, gettext_package).run()
  File "/usr/lib/python3.7/site-packages/ibus_cangjie/setup.py", line 35, in __init__
    self.__builder.add_from_file(ui_file)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/ibus-cangjie/setup.ui:43:36 Invalid property: GtkDialog.border_width (11)
```

After googling awhile, i found [similar problem](https://bugzilla.redhat.com/show_bug.cgi?id=1951884) also happened on Fedora 34 which uses GNOME 40 too. I believe it is due to Gtk4 which [deprecated GtkContainer class](https://docs.gtk.org/gtk4/migrating-3to4.html#stop-using-gtkcontainerborder-width) and thus the border-width property no longer exists.

I don't have any experience in programming with Gtk. Dose anyone have some suggestions?

**Comment by yookoala** [comment]
Hi. Thanks for the report. I'm using GNOME 40 and I confirm that the same happen to me. I believe the same issue was also reported in Red Hat's bugzilla [here](https://bugzilla.redhat.com/show_bug.cgi?id=1951884).

@bochecha: Do you have time to dig into the issue?

**Comment by bochecha** [comment]
None at all, not before at least a few months, sorry. :(

Le 16 août 2021 09:46:03 GMT+02:00, Koala Yeung ***@***.***> a écrit :
>Hi. Thanks for the report. I'm using GNOME 40 and I confirm that the same happen to me. I believe the same issue was also reported in Red Hat's bugzilla [here](https://bugzilla.redhat.com/show_bug.cgi?id=1951884).
>
***@***.***: Do you have time to dig into the issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Cangjians/ibus-cangjie/issues/99#issuecomment-899297131
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mbridon** [comment]
Hi all, sorry for the never ending delay.

I'm back with some good news, I just tried with GNOME 44, and the old fix from @mike-fabian all those years ago is still included in the package, and the prefs tool still works, so I'm closing this issue. :tada:
